# the param for the llm model, to init the foundation model.
model_used = "geneformer"
model_type = "CellClassifier"
#model_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/result/anno/geneformer/{organ}/checkpoint/'
#model_file = '../../case/models/geneformer/'
vocab_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/case/models/geneformer/gene_vocab.json'
gene_median_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/case/models/geneformer/gene_median_dict.json'
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/annotation/human/organs/{organ}/test.h5ad'  # h5ad for the sc express matrix
output_dir = '../../case/result/anno/geneformer/{organ}/'
device = 'cuda:2'
# annotation task
label_key = "cell_type_ontology_term_id"
gene_ensembl_key = 'feature_name'
epoches=20
batch_size=32
finetune=false