# the param for the llm model, to init the foundation model.
model_used = "scfoundation"
model_file = '../../case/models/scfoundation/models.ckpt'
vocab_file = '../../case/models/scfoundation/gene_vocab.json'
finetune_model = '../../case/result/anno/scf/{organ}/model_best.pt'
key = "cell"


# test h5ad, sc express matrix
n_bins = 100
input_file = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/case/data/annotation/human/organs/{organ}/train.h5ad'  # h5ad for the sc express matrix
output_dir = '../../case/result/anno/scf/all_genes/{organ}/'
device = 'cuda:2'
#quantile_cutoff = 0
finetune=true
distributed=true
lr=0.0001
batch_size = 8
epochs=30


# the input data info, for the preocess step
max_none_zero_num = 5000 # for encoder if GPU is OMM
max_seq_len = 19264
#n_hvg = 3000
label_key = "cell_type_ontology_term_id"

weight_bias_track = false
project_name = 'biollm_annotation'
exp_name = 'scf_{organ}'
