model_used = "scmamba" # scgpt/scmamba/st_performer
emb_type = 'cell' # gene/cell/gene-expression
model_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/mamba/gst_ori_initemb/best_model.pt'
model_param_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/mamba/gst_ori_initemb/args.json'
vocab_file = '/home/share/huadjyin/home/s_jiangwenjian/proj/scLLM/scGPT/saves/Pretraining/cellxgene/mamba/gst_ori_initemb/vocab.json'
input_file = '/home/share/huadjyin/home/s_huluni/project/bio_model/biollm/tutorials/zero-shot/cabe6d98-2da8-4cd4-a8dc-66726eeb104a.h5ad'  # h5ad for the sc express matrix
distributed = false
do_pretrain = false
output_dir = '/home/share/huadjyin/home/s_qiuping1/workspace/omics_model/bio_model/biollm/biollm/result/embeddings/'
device = 'cuda'
include_zero_gene = false
# the input data info, for the preocess step
hvg_number = 0
data_is_raw = false
input_style='binned'
task='Embedding'
pad_token = '<pad>'
pad_value = -2
batch_size = 32
mask_ratio = 0
CLS = false  # celltype classification objective
ADV = false  # Adversarial training for batch correction
CCE = false  # Contrastive cell embedding objective
MVC = false  # Masked value prediction for cell embedding
ECS = false  # Elastic cell similarity objective

